import TheHeader from '@/components/TheHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import TheFooter from '@/components/TheFooter'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Praktika-rehabilitacja',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={`font-main flex flex-col min-h-screen`}>
        <TheHeader/>  
          <main className='flex-grow'>
            {children}
          </main>      
        
        <TheFooter className="mt-auto" />
        </body>
    </html>
  )
}
